version: "3"
services:
  notebook:
    image: jupyter/datascience-notebook
    container_name: notebook
    ports:
        - "8888:8888"
    volumes:
        - "./src:/home/jovyan"
    command: start-notebook.sh --NotebookApp.token=''
    tty: true